name: weather
description: "A new Flutter project."
publish_to: "none"

version: 0.2.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  validatorless: ^1.2.5
  dio: ^5.9.0
  geolocator: ^14.0.2
  uuid: ^4.5.1
  http: ^1.5.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
